### ISSUE TITLE
Settings file is required to use the package

### ISSUE THREAD

**Issue by wigging** [ORNL/flowcept#147]
I cloned the repository and from within the project directory I pip installed flowcept in a Python environment. I tried to import the package with `import flowcept` but it gives the following exception:

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/g/Desktop/ORNL/OLCF/flowcept/src/flowcept/__init__.py", line 3, in <module>
    from flowcept.configs import SETTINGS_PATH
  File "/Users/g/Desktop/ORNL/OLCF/flowcept/src/flowcept/configs.py", line 19, in <module>
    raise Exception(
Exception: Settings file /Users/g/.flowcept/settings.yaml was not found. You should either define the environment variable FLOWCEPT_SETTINGS_PATH with its path or install Flowcept's package to create the directory ~/.flowcept with the file in it.
A sample settings file is found in the 'resources' directory under the project's root path.
```

Obviously it's looking for a settings file in my home directory but the implementation of this is a poor user experience. The user should not be required to create such a file just to use the package. Some options to fix this are:
- Have flowcept generate the file if it doesn't exist 
- Use default settings defined within the package if a settings file does not exist

**Comment by renan-souza** [comment]
Closing as this is a duplicate issue:
https://github.com/ORNL/flowcept/issues/119#issue-2176447007
