### ISSUE TITLE
Sphinx Documentation is not available for users

### ISSUE THREAD

**Issue by wigging** [ORNL/flowcept#170]
Sphinx documentation is available in the docs directory but there is no link to actually view the documentation. The only way to view the documentation is to download the repository, install/activate a virtual environment with the necessary dependencies, build the docs on your local machine, then view the generated HTML files in your local web browser. The docs need to be built and hosted with Read The Docs so a link is available for users to view the documentation website. This is standard practice for Python packages and is expected for this package too.

**Comment by renan-souza** [comment]
What do you need to make this available?

**Comment by renan-souza** [comment]
@wigging I'm an admin of this repo. Can you guide me through the steps?

**Comment by renan-souza** [comment]
@wigging The automatic addition didn't work. I will try to manually add the project, following these steps:
https://docs.readthedocs.io/en/stable/intro/add-project.html#manually-add-your-project

 Can you check if any modification is needed on this file to make it work on Flowcept?

https://github.com/ORNL/Zambeze/blob/main/.readthedocs.yaml

If not, I will just copy it and put it on Flowcept's repository.

**Comment by wigging** [comment]
I would add a `.readthedocs.yaml` to the repository before setting it up on Read The Docs website. The contents of the yaml file will be slightly different than the one used for zambeze. I can push up a branch with the changes later this week.

**Comment by renan-souza** [comment]
It's available at: https://flowcept.readthedocs.io/
